sudo: false

language: go

go:
  - 1.13.1

install:
  - go get -u golang.org/x/lint/golint
  - go get -t -v ./...

before_script:
  - go mod verify
  - golint -set_exit_status ./...

script:
  - go build -v ./cmd/server/main.go
